### ISSUE TITLE
how do i use this with swift 2.3 ?

### ISSUE THREAD

**Issue by srolesen** [Daniel1of1/CSwiftV#28]
I'm still dependant on cocoapods that are not properly updated to swift 3, can i use CSwiftV with swift 2.3 ?

**Comment by kevinmanase** [comment]
I'm actually having problems with Swift 3

**Comment by thully** [comment]
You should be able to use the latest code from Git on Swift 3 - you probably need an older version to use it on 2.3. If you have a project using Cocoapods, you'll have to manually update the CSwiftV source under Pods to the latest version, as cocoapods only has 0.0.5 (which does not work with Swift 3).

**Comment by srolesen** [comment]
I do not understand your reply, should I use some other install method than usual in order to get a version compatible with swift 2.3 ?

**Comment by Daniel1of1** [comment]
Hi @srolesen - A comment I posted on another issue might help: https://github.com/Daniel1of1/CSwiftV/issues/29#issuecomment-251667487

**Comment by Daniel1of1** [comment]
I'm going to close this since - If I understand correctly this is a viable solution - you can point to a different tag that was still 2.3 as well. If I have misunderstood let me know and I will reopen. I know it's not optimal. I better solution might be maintaining separate branches for versions, but I'm afraid I don't have the time to do this at the moment.
